#!/usr/bin/expect -f
set timeout -1
spawn bash -c "scp -o StrictHostKeyChecking=no db/01_schema.sql root@178.104.127.220:/root/01_schema_onlineclass.sql && ssh -o StrictHostKeyChecking=no root@178.104.127.220 'docker exec -i supabase-db psql -U postgres -d postgres < /root/01_schema_onlineclass.sql'"
expect "password:"
send "voibVmIdk9DqPMmZ\r"
expect "password:"
send "voibVmIdk9DqPMmZ\r"
expect eof
